### ISSUE TITLE
[Fabric][Figura0.1.5-rc6]When using these avatars in Figura0.1.5-rc6, the ears of the avatars are missing.

### ISSUE THREAD

**Issue by OvOla2** [Gakuto1112/SenkoSan#27] opened 2024-12-19 05:46 UTC
![2024-12-19_13 17 24](https://github.com/user-attachments/assets/9d671342-acea-4467-a891-9225bbade093)
![2024-12-19_13 15 10](https://github.com/user-attachments/assets/2548846c-db6f-48d3-a1e1-ca38407bdf98)
Strangely, Sora's ears didn't disappear.🤔
![2024-12-19_13 15 17](https://github.com/user-attachments/assets/bb5b49b0-eb62-4615-a690-8dfed847bfea)

**Comment by Gakuto1112** [comment] 2024-12-19 12:34
Thanks for using my avatar and reporting the issue!
This issue has been confirmed in my environment. I will identify the cause.

**Comment by Gakuto1112** [comment] 2024-12-19 12:46
@OvOla2
This issue was fixed in avatar version v1.25.9. Please update your avatar to the latest.
Thanks for reporting this issue!

**Closed as completed by Gakuto1112** 2024-12-19 12:46 UTC
Labels: bug
